# Generated by Django 6.1.1 on 2026-09-27 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_notice_created_at_notice_documents_to_carry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'placements_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSED', 'Parsed'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('duplicate_policy', models.CharField(default='skip', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placements_importsession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_sr_no', models.CharField(blank=True, default='', max_length=100)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], default='VALID', max_length=20)),
                ('validation_messages', models.JSONField(blank=True, default=list)),
                ('duplicate_info', models.JSONField(blank=True, default=dict)),
                ('is_selected', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='placements.importsession')),
            ],
            options={
                'db_table': 'placements_importedrow',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['session', 'row_number'], name='placements__session_ec1a66_idx'), models.Index(fields=['session', 'status'], name='placements__session_7210bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(db_index=True, max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('tech_nontech', models.CharField(choices=[('Tech', 'Tech'), ('Non-Tech', 'Non-Tech'), ('Both', 'Both')], default='Tech', max_length=20)),
                ('placement_internship', models.CharField(choices=[('Placement', 'Placement'), ('Internship', 'Internship'), ('Both', 'Both')], default='Placement', max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True, default='')),
                ('eligible_departments', models.JSONField(blank=True, default=list)),
                ('department_flags', models.JSONField(blank=True, default=dict)),
                ('job_profiles', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('emolument_raw', models.CharField(blank=True, default='', max_length=255)),
                ('emolument_value', models.FloatField(blank=True, null=True)),
                ('emolument_unit', models.CharField(blank=True, default='', max_length=50)),
                ('selection_process', models.TextField(blank=True, default='')),
                ('number_of_offers', models.IntegerField(blank=True, null=True)),
                ('source_sr_no', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='placements.company')),
                ('company_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_opportunities', to='placements.companyregistration')),
            ],
            options={
                'db_table': 'placements_opportunity',
                'indexes': [models.Index(fields=['batch', 'company'], name='placements__batch_4c2dc5_idx'), models.Index(fields=['batch', 'designation'], name='placements__batch_d135c5_idx')],
            },
        ),
    ]
