# Generated by Django 6.1.1 on 2026-09-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_company_importsession_importedrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementopportunity',
            name='designation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='placementopportunity',
            name='emolument_raw',
            field=models.TextField(blank=True, default=''),
        ),
    ]
