# Generated by Django 5.1.1 on 2026-09-28 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_alter_placementopportunity_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='placements.notice'),
        ),
        migrations.AddField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='placements.company'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notice',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='placements.placementopportunity'),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='version_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='NoticeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED_DRAFT', 'Created Draft'), ('UPDATED_DRAFT', 'Updated Draft'), ('PUBLISHED', 'Published'), ('UPDATED_VERSION', 'Updated Version'), ('CLONED', 'Cloned as New Notice'), ('ARCHIVED', 'Archived'), ('DELETED_DRAFT', 'Deleted Draft')], max_length=50)),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('performed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('performed_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='placements.notice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placements_notice_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NoticeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title_or_subject', models.CharField(max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('changes_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_versions', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='placements.notice')),
            ],
            options={
                'db_table': 'placements_notice_version',
                'ordering': ['-version_number'],
                'unique_together': {('notice', 'version_number')},
            },
        ),
    ]
